/// <reference types="node" />
// @vitest-environment node

import { execFile, spawn } from "node:child_process"
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises"
import { tmpdir } from "node:os"
import path from "node:path"
import { promisify } from "node:util"

import { describe, expect, it } from "vitest"

const execFileAsync = promisify(execFile)
const root = process.cwd()
const cliPath = path.join(root, "scripts", "agent-html-cli.mjs")

type CliSchemaJson = {
  readonly kind: string
  readonly components: readonly { readonly name: string }[]
}

type ArtifactConfigJson = {
  readonly density: string
}

describe("agent-html CLI", () => {
  it("prints agent-facing schema without implementation props", async () => {
    const { stdout } = await runCli(["schema", "--format", "json"])
    const schema = parseJson<CliSchemaJson>(stdout)
    const serialized = JSON.stringify(schema)

    expect(schema.kind).toBe("agent-html-cli-schema")
    expect(
      schema.components.some((item: { name: string }) => item.name === "page"),
    ).toBe(true)
    expect(serialized).not.toContain('"className"')
    expect(serialized).not.toContain('"style"')
  })

  it("writes schema output to a requested path", async () => {
    const tempDir = await mkdtemp(path.join(tmpdir(), "agent-html-cli-"))
    const outputPath = path.join(tempDir, "schema.txt")

    await runCli(["schema", "--format", "prompt", "--out", outputPath])

    await expect(readFile(outputPath, "utf8")).resolves.toContain(
      "Write agent-html only.",
    )
    await rm(tempDir, { force: true, recursive: true })
  })

  it("composes structured input into a valid agent-html document", async () => {
    const tempDir = await mkdtemp(path.join(tmpdir(), "agent-html-cli-"))
    const inputPath = path.join(tempDir, "input.json")
    const outputPath = path.join(tempDir, "artifact.agent.html")

    await writeFile(
      inputPath,
      JSON.stringify({
        meta: {
          theme: "neutral",
          density: "compact",
          tone: "dashboard",
          width: "dashboard",
        },
        document: {
          name: "page",
          props: { title: "CLI Demo" },
          children: [
            {
              name: "card",
              props: { title: "Overview" },
              children: ["Generated by compose"],
            },
          ],
        },
      }),
    )

    await runCli(["compose", "--input", inputPath, "--out", outputPath])

    await expect(readFile(outputPath, "utf8")).resolves.toContain(
      '<page title="CLI Demo">',
    )
    await rm(tempDir, { force: true, recursive: true })
  })

  it("composes the same input shape from stdin", async () => {
    const tempDir = await mkdtemp(path.join(tmpdir(), "agent-html-cli-"))
    const outputPath = path.join(tempDir, "artifact.agent.html")

    await runCliWithInput(
      ["compose", "--stdin", "--out", outputPath],
      JSON.stringify({
        document: {
          name: "page",
          props: { title: "Stdin Demo" },
          children: [{ name: "card", children: ["From stdin"] }],
        },
      }),
    )

    await expect(readFile(outputPath, "utf8")).resolves.toContain(
      '<page title="Stdin Demo">',
    )
    await rm(tempDir, { force: true, recursive: true })
  })

  it("rejects blocked implementation props before compose output", async () => {
    const tempDir = await mkdtemp(path.join(tmpdir(), "agent-html-cli-"))
    const inputPath = path.join(tempDir, "input.json")
    const outputPath = path.join(tempDir, "artifact.agent.html")

    await writeFile(
      inputPath,
      JSON.stringify({
        document: {
          name: "page",
          props: { title: "Blocked", className: "p-4" },
          children: [],
        },
      }),
    )

    await expectCliFailure(
      runCli(["compose", "--input", inputPath, "--out", outputPath]),
      "Blocked implementation prop",
    )
    await expect(readFile(outputPath, "utf8")).rejects.toMatchObject({
      code: "ENOENT",
    })
    await rm(tempDir, { force: true, recursive: true })
  })

  it("sets finite config values in an isolated config file", async () => {
    const tempDir = await mkdtemp(path.join(tmpdir(), "agent-html-cli-"))
    const configPath = path.join(tempDir, "agent-html.config.json")
    const env = { AGENT_HTML_CONFIG_PATH: configPath }

    await runCli(["config", "set", "density", "compact"], env)
    const { stdout } = await runCli(["config", "get"], env)
    const config = parseJson<ArtifactConfigJson>(stdout)

    expect(config.density).toBe("compact")
    await expectCliFailure(
      runCli(["config", "set", "density", "loose"], env),
      "Invalid value",
    )
    const persistedConfig = parseJson<ArtifactConfigJson>(
      await readFile(configPath, "utf8"),
    )

    expect(persistedConfig.density).toBe("compact")
    await rm(tempDir, { force: true, recursive: true })
  })

  it("builds a sanitized document into a static artifact directory", async () => {
    const tempDir = await mkdtemp(path.join(tmpdir(), "agent-html-cli-"))
    const inputPath = path.join(tempDir, "artifact.agent.html")
    const outputDir = path.join(tempDir, "html")

    await writeFile(
      inputPath,
      [
        '<meta-agent theme="neutral" density="compact" tone="dashboard" width="dashboard" />',
        '<page title="CLI Build"><card title="Overview">Built by CLI</card></page>',
      ].join("\n"),
    )

    await runCli(["build", "--input", inputPath, "--out", outputDir])

    await expect(
      readFile(path.join(outputDir, "index.html"), "utf8"),
    ).resolves.toContain("Built by CLI")
    await rm(tempDir, { force: true, recursive: true })
  }, 60000)

  it("rejects invalid build input before artifact generation", async () => {
    const tempDir = await mkdtemp(path.join(tmpdir(), "agent-html-cli-"))
    const inputPath = path.join(tempDir, "artifact.agent.html")
    const outputDir = path.join(tempDir, "html")

    await writeFile(
      inputPath,
      '<page title="Bad"><card className="x" /></page>',
    )

    await expectCliFailure(
      runCli(["build", "--input", inputPath, "--out", outputDir]),
      "unknown-attr",
    )
    await expect(
      readFile(path.join(outputDir, "index.html"), "utf8"),
    ).rejects.toMatchObject({
      code: "ENOENT",
    })
    await rm(tempDir, { force: true, recursive: true })
  })

  it("rejects invalid flags with a non-zero exit", async () => {
    await expectCliFailure(
      runCli(["schema", "--format"]),
      "--format requires a value.",
    )
  })
})

function runCli(args: readonly string[], env: NodeJS.ProcessEnv = {}) {
  return execFileAsync(process.execPath, [cliPath, ...args], {
    cwd: root,
    env: {
      ...process.env,
      ...env,
    },
  })
}

async function runCliWithInput(args: readonly string[], input: string) {
  await new Promise<void>((resolve, reject) => {
    let stderr = ""
    const child = spawn(process.execPath, [cliPath, ...args], {
      cwd: root,
      stdio: ["pipe", "ignore", "pipe"],
    })

    child.stderr.setEncoding("utf8")
    child.stderr.on("data", (chunk: string) => {
      stderr += chunk
    })
    child.on("error", reject)
    child.on("exit", (code) => {
      if (code === 0) {
        resolve()
        return
      }

      reject(new Error(stderr || `CLI exited with code ${code ?? "null"}`))
    })
    child.stdin.end(input)
  })
}

function parseJson<T>(source: string): T {
  return JSON.parse(source) as T
}

async function expectCliFailure(
  promise: Promise<unknown>,
  expectedStderr: string,
) {
  try {
    await promise
  } catch (error) {
    expect(getErrorStderr(error)).toContain(expectedStderr)
    return
  }

  throw new Error("Expected CLI command to fail.")
}

function getErrorStderr(error: unknown): string {
  if (
    error &&
    typeof error === "object" &&
    "stderr" in error &&
    typeof error.stderr === "string"
  ) {
    return error.stderr
  }

  return ""
}
