import type { ComponentSchemaOverlay } from "./types"

const TEXT_CHILD = "#text"

export const COMPONENT_SCHEMA_OVERLAYS = [
  {
    name: "page",
    description: "Document root component.",
    expose: true,
    sourceComponents: [],
    props: [
      {
        name: "title",
        valueKind: "string",
        required: true,
        description: "Visible page title.",
      },
    ],
    allowedChildren: [
      "alert",
      "card",
      "separator",
      "table",
      "list",
      "tabs",
      "accordion",
    ],
  },
  {
    name: "alert",
    description: "Important callout or warning.",
    expose: true,
    sourceComponents: ["Alert"],
    props: [
      {
        name: "title",
        valueKind: "string",
        description: "Callout heading.",
      },
      {
        name: "tone",
        valueKind: "enum",
        description: "Alert semantic tone.",
        enumValues: ["neutral", "danger"],
      },
    ],
    allowedChildren: [TEXT_CHILD],
    hiddenProps: ["variant"],
  },
  {
    name: "card",
    description: "Content grouping component.",
    expose: true,
    sourceComponents: ["Card"],
    props: [
      {
        name: "title",
        valueKind: "string",
        description: "Card heading.",
      },
    ],
    allowedChildren: [
      "alert",
      "badge",
      "checkbox",
      "input",
      "progress",
      "radio-group",
      "separator",
      "table",
      "textarea",
      "list",
      "tabs",
      "accordion",
      TEXT_CHILD,
    ],
    hiddenProps: ["size"],
  },
  {
    name: "separator",
    description: "Section divider.",
    expose: true,
    sourceComponents: ["Separator"],
    props: [],
    allowedChildren: [],
  },
  {
    name: "badge",
    description: "Short status label.",
    expose: true,
    sourceComponents: ["Badge"],
    props: [
      {
        name: "tone",
        valueKind: "enum",
        description: "Badge semantic tone.",
        enumValues: ["neutral", "success", "warning", "danger"],
      },
    ],
    allowedChildren: [TEXT_CHILD],
    hiddenProps: ["variant"],
  },
  {
    name: "progress",
    description: "Read-only completion indicator.",
    expose: true,
    sourceComponents: ["Progress"],
    props: [
      {
        name: "value",
        valueKind: "number",
        required: true,
        description: "Completion percentage from 0 to 100.",
      },
    ],
    allowedChildren: [],
  },
  {
    name: "input",
    description: "Single-line text field.",
    expose: true,
    sourceComponents: ["Input"],
    props: [
      {
        name: "label",
        valueKind: "string",
        required: true,
        description: "Visible field label.",
      },
      {
        name: "value",
        valueKind: "string",
        description: "Current field value.",
      },
      {
        name: "description",
        valueKind: "string",
        description: "Helpful field note.",
      },
    ],
    allowedChildren: [],
    hiddenProps: ["defaultValue", "placeholder", "type"],
  },
  {
    name: "textarea",
    description: "Multiline text field.",
    expose: true,
    sourceComponents: ["Textarea"],
    props: [
      {
        name: "label",
        valueKind: "string",
        required: true,
        description: "Visible field label.",
      },
      {
        name: "value",
        valueKind: "string",
        description: "Current field value.",
      },
      {
        name: "description",
        valueKind: "string",
        description: "Helpful field note.",
      },
    ],
    allowedChildren: [],
    hiddenProps: ["defaultValue", "placeholder"],
  },
  {
    name: "checkbox",
    description: "Single boolean field.",
    expose: true,
    sourceComponents: ["Checkbox"],
    props: [
      {
        name: "label",
        valueKind: "string",
        required: true,
        description: "Visible field label.",
      },
      {
        name: "checked",
        valueKind: "boolean",
        description: "Whether the field starts checked.",
      },
      {
        name: "description",
        valueKind: "string",
        description: "Helpful field note.",
      },
    ],
    allowedChildren: [],
    hiddenProps: ["defaultChecked"],
  },
  {
    name: "radio-group",
    description: "Single-select option field.",
    expose: true,
    sourceComponents: ["RadioGroup"],
    props: [
      {
        name: "label",
        valueKind: "string",
        required: true,
        description: "Visible field label.",
      },
      {
        name: "value",
        valueKind: "string",
        description: "Initially selected option value.",
      },
      {
        name: "description",
        valueKind: "string",
        description: "Helpful field note.",
      },
    ],
    allowedChildren: ["option"],
    hiddenProps: ["defaultValue"],
  },
  {
    name: "option",
    description: "Single selectable option.",
    expose: true,
    sourceComponents: ["RadioGroupItem"],
    props: [
      {
        name: "value",
        valueKind: "string",
        required: true,
        description: "Stable option value.",
      },
      {
        name: "label",
        valueKind: "string",
        required: true,
        description: "Visible option label.",
      },
    ],
    allowedChildren: [TEXT_CHILD],
  },
  {
    name: "table",
    description: "Structured tabular evidence.",
    expose: true,
    sourceComponents: ["Table"],
    props: [],
    allowedChildren: ["row"],
  },
  {
    name: "row",
    description: "Table row values.",
    expose: true,
    sourceComponents: ["TableRow"],
    props: [
      {
        name: "kind",
        valueKind: "enum",
        description: "Table row role.",
        enumValues: ["header", "body"],
      },
    ],
    allowedChildren: ["cell"],
  },
  {
    name: "cell",
    description: "Table cell content.",
    expose: true,
    sourceComponents: ["TableCell", "TableHead"],
    props: [],
    allowedChildren: [TEXT_CHILD],
  },
  {
    name: "list",
    description: "Ordered or unordered item list.",
    expose: true,
    sourceComponents: [],
    props: [
      {
        name: "variant",
        valueKind: "enum",
        description: "List marker style.",
        enumValues: ["ordered", "unordered"],
      },
    ],
    allowedChildren: ["item"],
  },
  {
    name: "item",
    description: "List item.",
    expose: true,
    sourceComponents: [],
    props: [],
    allowedChildren: [TEXT_CHILD],
  },
  {
    name: "tabs",
    description: "Interactive view switcher.",
    expose: true,
    sourceComponents: ["Tabs"],
    props: [
      {
        name: "default",
        valueKind: "string",
        description: "Initially selected tab value.",
      },
    ],
    allowedChildren: ["tab"],
    hiddenProps: ["defaultValue", "value"],
  },
  {
    name: "tab",
    description: "Single tabs view.",
    expose: true,
    sourceComponents: ["TabsContent", "TabsTrigger"],
    props: [
      {
        name: "value",
        valueKind: "string",
        required: true,
        description: "Stable tab value.",
      },
      {
        name: "label",
        valueKind: "string",
        required: true,
        description: "Visible tab label.",
      },
    ],
    allowedChildren: [
      "alert",
      "card",
      "checkbox",
      "input",
      "progress",
      "radio-group",
      "separator",
      "table",
      "textarea",
      "list",
      "accordion",
    ],
    hiddenProps: ["value"],
  },
  {
    name: "accordion",
    description: "Expandable section group.",
    expose: true,
    sourceComponents: ["Accordion"],
    props: [],
    allowedChildren: ["accordion-item"],
    hiddenProps: ["type", "collapsible"],
  },
  {
    name: "accordion-item",
    description: "Expandable section.",
    expose: true,
    sourceComponents: ["AccordionItem"],
    props: [
      {
        name: "value",
        valueKind: "string",
        required: true,
        description: "Stable accordion item value.",
      },
      {
        name: "title",
        valueKind: "string",
        required: true,
        description: "Visible section title.",
      },
    ],
    allowedChildren: [
      "alert",
      "badge",
      "checkbox",
      "input",
      "progress",
      "radio-group",
      "table",
      "textarea",
      "list",
      TEXT_CHILD,
    ],
    hiddenProps: ["value"],
  },
] as const satisfies readonly ComponentSchemaOverlay[]
